### ISSUE TITLE
Feature request: export validator::Validate directly from package_json_schema

### ISSUE THREAD

**Issue by nickfla1** [ifiokjr/package_json_schema#1]
## Description

Export `validator::Validate` directly from `package_json_schema`.

## Motivation

Allow crate's users to directly import `validator::Validate` from `package_json_schema`: right now you need to manully specify the depency in your `cargo.toml`

Something like:
```rs
use package_json_schema::{ PackageJson, validator::Validate };
```

<hr />

I think it should be fairly to implement as well. I was thinking something like this:
```rs 
// File: src/lib.rs

cfg_if! {
  if #[cfg(feature = "validate")] {
    mod utils; // Taken from current implementation
    pub mod validator;  
  }
}
```

If you think it might be a good addition I'm willing to contribute myself :D

**Comment by ifiokjr** [comment]
That would be great!
